### PR TITLE
Add an ability to process compressed messages

### PR DESCRIPTION
**Pull request by ndemidenko**
Add an ability to publish/consume compressed messages.
SQS/SNS allows to publish messages with maximum body size of 256 kb. By compressing message body we can exceed this limit

### CODE REVIEW

**Review by alexidt — DISMISSED** [review]

**Comment by AlexeyBogdan95** [comment]
Hi @ndemidenko. Do you still need this feature? Thanks.

**Comment by ndemidenko** [comment]
> Hi @ndemidenko. Do you still need this feature? Thanks.

Hi @AlexeyBogdan95, it would be nice to have this feature

**Comment by AlexeyBogdan95** [comment]
Hi @ndemidenko. Could you please rebase your changes from master branch? Thanks.

**Comment by AlexeyBogdan95** [comment]
Also, can I ask you to add tests to cover compression/decompression stuff?

**Comment by ndemidenko** [comment]
> Also, can I ask you to add tests to cover compression/decompression stuff?

@AlexeyBogdan95 Added, please review

**Pull request closed without merging**
